databases:
  - name: poligraph-db
    plan: free
    databaseName: poligraph
    user: poligraph

services:
  - type: web
    plan: free
    name: poligraph
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python manage.py check_db --max-attempts 60 --wait-seconds 5 && python -m gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poligraph-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: DEBUG_RENDER
        value: true 